# Generated by Django 4.0.6 on 2022-07-26 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='min_buyurtma',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='olchov',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='media',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ichki_mahsulot', to='asosiy.mahsulot'),
        ),
    ]
